//
//  ContentView.swift
//  Giggle
//
//  Created by Karan Arora on 10/25/24.
//

import SwiftUI
import SwiftData

// TODO
// Make ContentView a wrapper?
// Put components in different files for better organization - semi-done

struct ContentView: View {
    @Environment(\.modelContext) private var context
    @State private var searchText = ""
    @Query private var memes: [Meme]
    
    // Moved filtering logic here
    var filteredMemes: [Meme] {
        if searchText.isEmpty {
//            DataManager.clearDB(context: context)
            return memes
        } else {
//            DataManager.clearDB(context: context)
            return DataManager.findSimilarEntries(query: searchText, context: context, limit: 50, tagName:nil)
        }
    }

    var body: some View {
        NavigationStack {
            VStack {
                PageHeader(text: "Giggle")

                SearchBar(text: "Search for a Giggle", searchText: $searchText)
                    ScrollView {
                        LazyVGrid(columns: GridStyle.grid, spacing: GridStyle.folderRowPadding) {
                            if searchText.isEmpty {
                                FolderItem(text: "Favorites", isPinned: true)
                                FolderItem(text: "Recently Shared", isPinned: true)
                                FolderItem(text: "All Giggles", isPinned: true)
                                // these below need to be updates to actually reflect the autogenerated tags
                                FolderItem(text: "Sad")
                                FolderItem(text: "Sports")
                                FolderItem(text: "Surprised")
                            } else {
                                ForEach(filteredMemes) { meme in
                                    GiggleItem(meme: meme)
                                }
                            }
                        }
                        .padding(.horizontal, GridStyle.columnPadding)
                        .padding(.top, GridStyle.searchBarPadding)
                    }

                BottomNavBar()
            }
            .background(Colors.backgroundColor.ignoresSafeArea())
        }.tint(.black)
    }
}

#Preview {
    ContentView()
}
